version: '3.8'
services:
  web:
    build: ./web
    container_name: web
    hostname: web
    volumes:
      - ./web/conf/conf.d/:/etc/nginx/conf.d
    ports:
      - "8080:8000"
    environment:
      TZ: 'Asia/Tokyo'
    depends_on:
      - app
    networks:
      app_net:
        ipv4_address: 192.168.1.111

  db:
    build: ./db
    container_name: db
    hostname: db
    # command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - ./db/mysql/:/var/lib/mysql/
      - ./db/.bashrc:/root/.bashrc
    networks:
      app_net:
        ipv4_address: 192.168.1.112

  app:
    build: ./app
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    container_name: app
    hostname: app
    ports:
      - "3000:3000"
    volumes:
      - ./app:/usr/src/app
    environment:
      TZ: 'Asia/Tokyo'
    depends_on:
      - db
    networks:
      app_net:
        ipv4_address: 192.168.1.113

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24

volumes:
  mysql: